name: link-your-issues

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

jobs:
  link-your-issues:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-automation/link-your-issues@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
